import React from "react";
import { Metadata } from "next";
import EcommerceProvider from "../store/EcommerceProvider";
import Navbar from "@/components/Common/Navbar";
import Footer from "@/components/Common/Footer";
import QueryClientProvider from "@/store/QueryProvider";

import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EcommerceProvider>
          <QueryClientProvider>
            <Navbar />
            {children}
            <Footer />
          </QueryClientProvider>
        </EcommerceProvider>
      </body>
    </html>
  );
}
