const dataLeft = [
  {
    label: "Categorias",
    name: "categories",
    required: true,
    type: "text",
    placeholder: "Tops, Bottoms, Shoes, Accesories",
  },
  {
    label: "Collecion/Season",
    name: "season",
    required: true,
    type: "text",
    placeholder: "Temporada: Invierno, Verano, Otono, Primavera etc",
  },
  {
    label: "Descripcion en ingles",
    name: "description_en",
    required: true,
    type: "text",
    placeholder: "Descripcion en ingles",
  },
  {
    label: "Descripcion en español",
    name: "description_es",
    required: true,
    type: "text",
    placeholder: "Description en español",
  },
  {
    label: "Nombre en ingles",
    name: "name_en",
    required: true,
    type: "text",
    placeholder: "Nombre en  INGLES",
  },
  {
    label: "Nombre en Español",
    name: "name_es",
    required: true,
    type: "text",
    placeholder: "Nombre",
  },
  {
    label: "Precio en DOLARES",
    name: "price_en",
    required: true,
    type: "number",
    placeholder: "Precio sin $",
  },
  {
    label: "Precio en pesos",
    name: "price_es",
    required: true,
    type: "number",
    placeholder: "Precio sin $",
  },
  {
    label: "url imagen principal",
    name: "image0",
    required: true,
    type: "text",
    placeholder: "www.IMAGEN_PRINCIPAL.com",
  },
  {
    label: "Proveedor",
    name: "provider",
    required: true,
    type: "text",
    placeholder: "Nombre Del Proveedor",
  },
  {
    label: "url imagen secundaria",
    name: "image1",
    required: true,
    type: "text",
    placeholder: "www.IMAGEN_SECUNDARIA.com",
  },
  {
    label: "Costo del Proveedor",
    name: "provider_cost",
    required: true,
    type: "number",
    placeholder: "Precio sin $",
  },
  {
    label: "url imagen tercearia",
    name: "image2",
    required: true,
    type: "text",
    placeholder: "www.IMAGEN_TERCEARIA.com",
  },
  {
    label: "url imagen ultima",
    name: "image3",
    required: true,
    type: "text",
    placeholder: "www.IMAGEN_ULTIMA.com",
  },
];

export { dataLeft };
